---
application:
  name: "mernprofilesserver"
  project: "MernProfilesServer"
  organization: "QoveryCommunity"
routers:
- name: "main-mernprofilesserver"
  routes:
  - application_name: "mernprofilesserver"
    paths:
    - "/*"
